services:
  airdrop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airdrop
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
        window: 1h
    environment:
      - SIKKANODE=${SIKKANODE}
      - PRIVATEKEY=${PRIVATEKEY}
      - TELEGRAMTOKEN=${TELEGRAMTOKEN}
      - TELEGRAMGROUP=${TELEGRAMGROUP}
