services:
  airdrop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airdrop
    restart: unless-stopped
    volumes:
      - airdrop-data:/data
    environment:
      - SIKKANODE=${SIKKANODE:-https://1.sikkalabs.com}
      - PRIVATEKEY=${PRIVATEKEY}
      - TELEGRAMTOKEN=${TELEGRAMTOKEN}
      - TELEGRAMGROUP=${TELEGRAMGROUP}
      - AIRDROP_DIVISOR=2000

volumes:
  airdrop-data:
