services:
  airdrop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airdrop
    restart: unless-stopped
    volumes:
      - airdrop-data:/data
    environment:
      - SIKKANODE=${SIKKANODE:-https://2.sikkalabs.com}
      - PRIVATEKEY=${PRIVATEKEY}
      - TELEGRAMTOKEN=${TELEGRAMTOKEN}
      - TELEGRAMGROUP=${TELEGRAMGROUP}

volumes:
  airdrop-data:
